"""DingDongDitch — browser execution infrastructure (plan-consuming runtime).

Public API for typed contracts and execute_operation / execute_plan.
Does not include a planner, site explorer, or workflow author.
"""

__version__ = "0.5.1"

from dingdongditch.contract.browser import (
    BrowserChannel,
    BrowserConfig,
    BrowserEngine,
    BrowserProvider,
    BrowserProfile,
    default_browser_config,
)
from dingdongditch.contract.expectation import Expectation, ExpectationType
from dingdongditch.contract.network import (
    NetworkArtifactKind,
    NetworkArtifactRequest,
    NetworkUrlMatchMode,
)
from dingdongditch.contract.dialog import DialogAction, DialogContract, DialogRequirement, DialogType
from dingdongditch.contract.screenshot import (
    DesktopRedactionRegion,
    ScreenshotConfig,
    ScreenshotPolicy,
)
from dingdongditch.contract.operation import (
    Action,
    ActionType,
    FreshnessPolicy,
    KeyPressScope,
    Locator,
    LocatorStrategy,
    Operation,
    OperationGuard,
    GuardBranch,
    TargetAbsentGuard,
    SelectMode,
)
from dingdongditch.contract.page_precondition import (
    FragmentPolicy,
    PageCondition,
    PageConditionResult,
    PageConditionResultValue,
    PageConditionType,
    PagePrecondition,
    PagePreconditionEvaluation,
)
from dingdongditch.contract.wait import LoadState, WaitCondition, WaitConditionType
from dingdongditch.contract.plan import (
    CompletionStatus,
    ExecutionPlan,
    FailurePolicy,
    PlanReceipt,
    PlanVerdict,
)
from dingdongditch.contract.receipt import ExecutionReceipt
from dingdongditch.contract.authority import (
    AuthorityEnvelope,
    AuthorityFirewall,
    FirewallDecision,
    FirewallOutcome,
    ProvenanceClass,
    merge_provenance,
    policy_hash,
)
from dingdongditch.contract.transaction import (
    CommitRejectedReason,
    CommitResult,
    PreparedOperation,
    PreparationStatus,
    TwoPhaseCommitError,
)
from dingdongditch.contract.quorum import (
    EvidenceSourceClass,
    QuorumResult,
    VerificationCheck,
    VerificationPolicy,
    VerificationQuorum,
    evaluate_quorum,
)
from dingdongditch.contract.receipt_chain import (
    RECEIPT_CHAIN_VERSION,
    ReceiptChainCheckpoint,
    ReceiptChainVerification,
    chain_receipt,
    hash_receipt,
    make_receipt_chain_checkpoint,
    verify_receipt_chain_against_checkpoint,
    verify_receipt_chain,
    verify_receipt_hash,
)
from dingdongditch.contract.handoff import AgentHandoff, AgentHandoffCheckpoint
from dingdongditch.contract.signed_plan import (
    SIGNED_PLAN_ALGORITHM,
    SIGNED_PLAN_VERSION,
    SignedPlanAuthority,
    SignedPlanError,
    SignedPlanVerification,
    TrustedPlanSigner,
    TrustedPlanVerifier,
    canonical_plan_hash,
)
from dingdongditch.contract.identity import (
    IDENTITY_ALGORITHM,
    IDENTITY_VERSION,
    AgentIdentity,
    IdentityAssertion,
    IdentityError,
    IdentityKey,
    IdentityRegistry,
    IdentitySigner,
    IdentityStatus,
    identity_reference,
)
from dingdongditch.contract.mutation import (
    MutationActor,
    MutationArbitrationError,
    MutationArbitrationPolicy,
    MutationEvidence,
)
from dingdongditch.contract.attestation import (
    ATTESTATION_ALGORITHM,
    ATTESTATION_VERSION,
    AssuranceLevel,
    AttestationError,
    AttesterTrustRegistry,
    ExecutionAttestation,
    ExecutionAttestationStatement,
    ExternalAttesterAdapter,
    HostEd25519Attester,
    make_execution_attestation_statement,
)
from dingdongditch.contract.speculation import (
    BranchPreparation,
    BranchSelection,
    BranchSelectionStatus,
    SpeculationExecutionResult,
    SpeculativeBranch,
    SpeculativePlan,
)
from dingdongditch.contract.target import (
    AttributeOperator,
    CardinalityPolicy,
    ConstraintType,
    NameMatchMode,
    TargetConstraint,
)
from dingdongditch.contract.verdict import Verdict
from dingdongditch.runtime.executor import execute_operation
from dingdongditch.runtime.plan_executor import execute_plan
from dingdongditch.plan_builder import PlanBuilder
from dingdongditch.inspection import inspect_target, list_dialog_history, observe_page
from dingdongditch.runtime.session import SessionCheckpoint, SessionPhase, SessionStatus
from dingdongditch.runtime.typing_session import (
    TypingSession,
    TypingSessionConfig,
    TypingSessionResult,
    TypingKeyReceipt,
)
from dingdongditch.contract.download import (
    DownloadArtifact, DownloadArtifactStore, DownloadChecksumPolicy,
    DownloadCollisionPolicy, DownloadCoordinator, DownloadEventMonitor,
    DownloadFailureReason, DownloadLifecycleState, DownloadPageEffectPolicy,
    DownloadMimeSource, DownloadPolicy, DownloadRequest, DownloadResult,
    DownloadTriggerAction,
    SafeFilenameResolver, CollisionResolver, DownloadIntegrityVerifier,
    StagingRecoveryManager,
    TrustedDownloadConfig,
)
from dingdongditch.contract.pointer import PointerMoveRequest, PointerOrigin
from dingdongditch.contract.upload import UploadAuthorization, UploadValidationError
from dingdongditch.contract.combobox import ComboboxSelection
from dingdongditch.contract.observation import (
    CandidateEvidenceLevel,
    LocatorAttestation,
    LocatorAttestationStatus,
    ObservationCommit,
    ObservationEvidenceView,
    ObservationFreshnessResult,
    ObservationReference,
    ObservationTransactionEvidence,
    ObservationTransactionState,
    PageObservation,
    PageObservationOptions,
    SnapshotCore,
)
from dingdongditch.contract.application_lifecycle import (
    ApplicationLifecycleEvidence,
    ApplicationLifecycleState,
)
from dingdongditch.runtime.application_lifecycle import (
    ApplicationLifecycleAdapter,
    ChatGPTApplicationLifecycleAdapter,
    GeminiApplicationLifecycleAdapter,
    UnknownApplicationLifecycleAdapter,
    select_application_lifecycle_adapter,
)
from dingdongditch.page_observer import PageObserver
from dingdongditch.continuity import (
    BrowserBinding,
    CommandRecord,
    CommandState,
    ContinuityError,
    ContinuitySession,
    SessionHeader,
    SessionLifecycle,
    TerminalClassification,
    TransportKind,
)
from dingdongditch.runtime.stateful_session import (
    PublicSessionStatus,
    SessionFailureKind,
    SessionInfo,
    SessionObservation,
    SessionOperationResult,
    SessionPlanResult,
    SessionTypingResult,
    StatefulSessionError,
    StatefulSessionRuntime,
    cleanup_expired_sessions,
    close_session,
    execute_session_operation,
    prepare_session_operation,
    commit_session_operation,
    list_session_preparations,
    get_session_receipt_chain,
    get_session_receipt_chain_checkpoint,
    prepare_agent_handoff,
    claim_agent_handoff,
    execute_session_plan,
    get_session,
    inspect_session_dialogs,
    inspect_session_pages,
    observe_session_page,
    open_session,
    select_session_page,
)
from dingdongditch.runtime.governed_agent import (
    GovernedAgentService,
    GovernedAgentSession,
    TrustedHostRuntime,
)
from dingdongditch.planner import (
    PLANNER_INTERFACE_VERSION,
    PlannerAdapter,
    PlannerResponse,
    navigate_operation,
    click_operation,
    fill_operation,
    press_operation,
    scroll_operation,
    select_operation,
)
from dingdongditch.authentication import (
    AuthEvent, AuthEventType, AuthenticationCallbacks, AuthenticationCapability,
    AuthenticationError, AuthenticationFailureKind, MappingSecretProvider,
    ProfileInfo, ProfileManager, SecretProvider, SecretReference,
    SecretBinding, SecretResolutionReceipt, SecretValue, redact,
    PORTABLE_STATE_SCHEMA_VERSION, PortableStateFeature, PortableStatePolicy,
    PortableStateReceipt,
    CallbackWebAuthnTransport, WebAuthnParticipationReceipt,
    WebAuthnParticipationRequest, WebAuthnParticipationStatus, WebAuthnTransport,
    WebAuthnTransportEvent, WebAuthnTransportResult,
)
from dingdongditch.machine_contract import (
    MACHINE_CONTRACT_VERSION,
    ContractValidationError,
    PlanDocument,
    ValidationIssue,
    execution_plan_schema,
    execution_plan_tool,
    execution_receipt_schema,
    execution_schema,
    observation_schema,
    operation_schema,
    parse_execution_plan,
    parse_execution_receipt,
    parse_operation,
    parse_plan_document,
    parse_plan_receipt,
    parse_receipt,
    plan_document_schema,
    plan_receipt_schema,
    prepared_operation_schema,
    agent_handoff_checkpoint_schema,
    agent_handoff_schema,
    signed_plan_authority_schema,
    parse_signed_plan_authority,
    agent_identity_schema,
    identity_assertion_schema,
    parse_identity_assertion,
    mutation_evidence_schema,
    execution_attestation_schema,
    parse_execution_attestation,
    speculative_plan_schema,
    parse_speculative_plan,
    published_schema_resource,
    public_schema_names,
    serialize_execution_plan,
    serialize_plan_document,
)

__all__ = [
    "__version__",
    "Operation",
    "OperationGuard",
    "GuardBranch",
    "TargetAbsentGuard",
    "Action",
    "ActionType",
    "KeyPressScope",
    "SelectMode",
    "WaitCondition",
    "WaitConditionType",
    "LoadState",
    "Locator",
    "LocatorStrategy",
    "FreshnessPolicy",
    "PageConditionType",
    "FragmentPolicy",
    "PageCondition",
    "PagePrecondition",
    "PageConditionResultValue",
    "PageConditionResult",
    "PagePreconditionEvaluation",
    "Expectation",
    "ExpectationType",
    "NetworkUrlMatchMode",
    "NetworkArtifactKind",
    "NetworkArtifactRequest",
    "DialogType",
    "DialogAction",
    "DialogRequirement",
    "DialogContract",
    "ScreenshotPolicy",
    "ScreenshotConfig",
    "DesktopRedactionRegion",
    "Verdict",
    "ExecutionReceipt",
    "AuthorityEnvelope",
    "AuthorityFirewall",
    "FirewallDecision",
    "FirewallOutcome",
    "ProvenanceClass",
    "merge_provenance",
    "policy_hash",
    "PreparedOperation",
    "PreparationStatus",
    "CommitResult",
    "CommitRejectedReason",
    "TwoPhaseCommitError",
    "EvidenceSourceClass",
    "VerificationPolicy",
    "VerificationCheck",
    "VerificationQuorum",
    "QuorumResult",
    "evaluate_quorum",
    "RECEIPT_CHAIN_VERSION",
    "ReceiptChainCheckpoint",
    "ReceiptChainVerification",
    "hash_receipt",
    "verify_receipt_hash",
    "verify_receipt_chain",
    "verify_receipt_chain_against_checkpoint",
    "make_receipt_chain_checkpoint",
    "chain_receipt",
    "AgentHandoff",
    "AgentHandoffCheckpoint",
    "SIGNED_PLAN_VERSION",
    "SIGNED_PLAN_ALGORITHM",
    "SignedPlanAuthority",
    "SignedPlanError",
    "SignedPlanVerification",
    "TrustedPlanSigner",
    "TrustedPlanVerifier",
    "canonical_plan_hash",
    "IDENTITY_VERSION",
    "IDENTITY_ALGORITHM",
    "AgentIdentity",
    "IdentityKey",
    "IdentityAssertion",
    "IdentitySigner",
    "IdentityRegistry",
    "IdentityStatus",
    "IdentityError",
    "identity_reference",
    "MutationActor",
    "MutationArbitrationPolicy",
    "MutationArbitrationError",
    "MutationEvidence",
    "ATTESTATION_VERSION",
    "ATTESTATION_ALGORITHM",
    "AssuranceLevel",
    "AttestationError",
    "ExecutionAttestationStatement",
    "ExecutionAttestation",
    "HostEd25519Attester",
    "ExternalAttesterAdapter",
    "AttesterTrustRegistry",
    "make_execution_attestation_statement",
    "SpeculativeBranch",
    "SpeculativePlan",
    "BranchPreparation",
    "BranchSelection",
    "BranchSelectionStatus",
    "SpeculationExecutionResult",
    "execute_operation",
    "execute_plan",
    "ExecutionPlan",
    "PlanReceipt",
    "PlanVerdict",
    "CompletionStatus",
    "FailurePolicy",
    "TargetConstraint",
    "ConstraintType",
    "AttributeOperator",
    "NameMatchMode",
    "CardinalityPolicy",
    "BrowserConfig",
    "BrowserProvider",
    "BrowserEngine",
    "BrowserChannel",
    "BrowserProfile",
    "default_browser_config",
    "AuthEvent", "AuthEventType", "AuthenticationCallbacks",
    "AuthenticationCapability", "AuthenticationError", "AuthenticationFailureKind",
    "MappingSecretProvider", "ProfileInfo", "ProfileManager", "SecretProvider",
    "SecretReference", "SecretBinding", "SecretResolutionReceipt", "SecretValue", "redact",
    "PORTABLE_STATE_SCHEMA_VERSION", "PortableStateFeature", "PortableStatePolicy",
    "PortableStateReceipt",
    "WebAuthnParticipationRequest", "WebAuthnParticipationReceipt",
    "WebAuthnParticipationStatus", "WebAuthnTransport", "WebAuthnTransportEvent",
    "WebAuthnTransportResult", "CallbackWebAuthnTransport",
    "PlanBuilder",
    "inspect_target",
    "list_dialog_history",
    "observe_page",
    "SessionCheckpoint",
    "SessionPhase",
    "SessionStatus",
    "TypingSession",
    "TypingSessionConfig",
    "TypingSessionResult",
    "TypingKeyReceipt",
    "DownloadRequest",
    "DownloadPolicy",
    "DownloadCollisionPolicy",
    "DownloadChecksumPolicy",
    "DownloadPageEffectPolicy",
    "DownloadTriggerAction",
    "DownloadLifecycleState",
    "DownloadFailureReason",
    "DownloadMimeSource",
    "DownloadArtifact",
    "DownloadResult",
    "DownloadArtifactStore",
    "SafeFilenameResolver",
    "CollisionResolver",
    "DownloadIntegrityVerifier",
    "DownloadCoordinator",
    "DownloadEventMonitor",
    "StagingRecoveryManager",
    "TrustedDownloadConfig",
    "PointerMoveRequest",
    "PointerOrigin",
    "UploadAuthorization",
    "UploadValidationError",
    "ComboboxSelection",
    "PageObservation",
    "PageObservationOptions",
    "ObservationReference",
    "ObservationFreshnessResult",
    "SnapshotCore",
    "ObservationCommit",
    "ObservationTransactionEvidence",
    "ObservationTransactionState",
    "CandidateEvidenceLevel",
    "LocatorAttestation",
    "LocatorAttestationStatus",
    "ObservationEvidenceView",
    "PageObserver",
    "ContinuitySession",
    "ContinuityError",
    "SessionHeader",
    "SessionLifecycle",
    "CommandRecord",
    "CommandState",
    "BrowserBinding",
    "TransportKind",
    "TerminalClassification",
    "ApplicationLifecycleState",
    "PublicSessionStatus",
    "SessionFailureKind",
    "SessionInfo",
    "SessionObservation",
    "SessionOperationResult",
    "SessionPlanResult",
    "SessionTypingResult",
    "StatefulSessionError",
    "StatefulSessionRuntime",
    "TrustedHostRuntime",
    "GovernedAgentSession",
    "GovernedAgentService",
    "PLANNER_INTERFACE_VERSION",
    "PlannerAdapter",
    "PlannerResponse",
    "navigate_operation",
    "click_operation",
    "fill_operation",
    "press_operation",
    "scroll_operation",
    "select_operation",
    "open_session",
    "get_session",
    "observe_session_page",
    "execute_session_operation",
    "prepare_session_operation",
    "commit_session_operation",
    "list_session_preparations",
    "get_session_receipt_chain",
    "get_session_receipt_chain_checkpoint",
    "prepare_agent_handoff",
    "claim_agent_handoff",
    "execute_session_plan",
    "inspect_session_pages",
    "select_session_page",
    "inspect_session_dialogs",
    "close_session",
    "cleanup_expired_sessions",
    "ApplicationLifecycleEvidence",
    "ApplicationLifecycleAdapter",
    "ChatGPTApplicationLifecycleAdapter",
    "GeminiApplicationLifecycleAdapter",
    "UnknownApplicationLifecycleAdapter",
    "select_application_lifecycle_adapter",
    "MACHINE_CONTRACT_VERSION",
    "PlanDocument",
    "ValidationIssue",
    "ContractValidationError",
    "plan_document_schema",
    "execution_schema",
    "execution_plan_schema",
    "execution_plan_tool",
    "operation_schema",
    "observation_schema",
    "execution_receipt_schema",
    "plan_receipt_schema",
    "prepared_operation_schema",
    "agent_handoff_checkpoint_schema",
    "agent_handoff_schema",
    "signed_plan_authority_schema",
    "agent_identity_schema",
    "identity_assertion_schema",
    "mutation_evidence_schema",
    "execution_attestation_schema",
    "speculative_plan_schema",
    "parse_speculative_plan",
    "parse_execution_attestation",
    "public_schema_names",
    "published_schema_resource",
    "parse_plan_document",
    "parse_execution_plan",
    "parse_operation",
    "parse_signed_plan_authority",
    "parse_identity_assertion",
    "serialize_plan_document",
    "serialize_execution_plan",
    "parse_execution_receipt",
    "parse_plan_receipt",
    "parse_receipt",
]
