"""DingDongDitch — browser execution infrastructure (plan-consuming runtime).

Public API for typed contracts and execute_operation / execute_plan.
Does not include a planner, site explorer, or workflow author.
"""

__version__ = "0.4.1"

from dingdongditch.contract.browser import (
    BrowserChannel,
    BrowserConfig,
    BrowserEngine,
    BrowserProvider,
    BrowserProfile,
    default_browser_config,
)
from dingdongditch.contract.expectation import Expectation, ExpectationType
from dingdongditch.contract.network import (
    NetworkArtifactKind,
    NetworkArtifactRequest,
    NetworkUrlMatchMode,
)
from dingdongditch.contract.dialog import DialogAction, DialogContract, DialogRequirement, DialogType
from dingdongditch.contract.screenshot import (
    DesktopRedactionRegion,
    ScreenshotConfig,
    ScreenshotPolicy,
)
from dingdongditch.contract.operation import (
    Action,
    ActionType,
    FreshnessPolicy,
    KeyPressScope,
    Locator,
    LocatorStrategy,
    Operation,
    OperationGuard,
    GuardBranch,
    TargetAbsentGuard,
    SelectMode,
)
from dingdongditch.contract.page_precondition import (
    FragmentPolicy,
    PageCondition,
    PageConditionResult,
    PageConditionResultValue,
    PageConditionType,
    PagePrecondition,
    PagePreconditionEvaluation,
)
from dingdongditch.contract.wait import LoadState, WaitCondition, WaitConditionType
from dingdongditch.contract.plan import (
    CompletionStatus,
    ExecutionPlan,
    FailurePolicy,
    PlanReceipt,
    PlanVerdict,
)
from dingdongditch.contract.receipt import ExecutionReceipt
from dingdongditch.contract.target import (
    AttributeOperator,
    CardinalityPolicy,
    ConstraintType,
    NameMatchMode,
    TargetConstraint,
)
from dingdongditch.contract.verdict import Verdict
from dingdongditch.runtime.executor import execute_operation
from dingdongditch.runtime.plan_executor import execute_plan
from dingdongditch.plan_builder import PlanBuilder
from dingdongditch.inspection import inspect_target, list_dialog_history, observe_page
from dingdongditch.runtime.session import SessionCheckpoint, SessionPhase, SessionStatus
from dingdongditch.runtime.typing_session import (
    TypingFocusPolicy,
    TypingSession,
    TypingSessionConfig,
    TypingSessionResult,
    TypingKeyReceipt,
)
from dingdongditch.contract.download import (
    DownloadArtifact, DownloadArtifactStore, DownloadChecksumPolicy,
    DownloadCollisionPolicy, DownloadCoordinator, DownloadEventMonitor,
    DownloadFailureReason, DownloadLifecycleState, DownloadPageEffectPolicy,
    DownloadMimeSource, DownloadPolicy, DownloadRequest, DownloadResult,
    DownloadTriggerAction,
    SafeFilenameResolver, CollisionResolver, DownloadIntegrityVerifier,
    StagingRecoveryManager,
    TrustedDownloadConfig,
)
from dingdongditch.contract.pointer import PointerMoveRequest, PointerOrigin
from dingdongditch.contract.upload import UploadAuthorization, UploadValidationError
from dingdongditch.contract.combobox import ComboboxSelection
from dingdongditch.contract.observation import (
    CandidateEvidenceLevel,
    LocatorAttestation,
    LocatorAttestationStatus,
    ObservationCommit,
    ObservationEvidenceView,
    ObservationFreshnessResult,
    ObservationReference,
    ObservationTransactionEvidence,
    ObservationTransactionState,
    PageObservation,
    PageObservationOptions,
    SnapshotCore,
)
from dingdongditch.contract.application_lifecycle import (
    ApplicationLifecycleEvidence,
    ApplicationLifecycleState,
)
from dingdongditch.runtime.application_lifecycle import (
    ApplicationLifecycleAdapter,
    ChatGPTApplicationLifecycleAdapter,
    GeminiApplicationLifecycleAdapter,
    UnknownApplicationLifecycleAdapter,
    select_application_lifecycle_adapter,
)
from dingdongditch.page_observer import PageObserver
from dingdongditch.continuity import (
    BrowserBinding,
    CommandRecord,
    CommandState,
    ContinuityError,
    ContinuitySession,
    SessionHeader,
    SessionLifecycle,
    TerminalClassification,
    TransportKind,
)
from dingdongditch.runtime.stateful_session import (
    PublicSessionStatus,
    SessionFailureKind,
    SessionInfo,
    SessionObservation,
    SessionOperationResult,
    SessionPlanResult,
    StatefulSessionError,
    StatefulSessionRuntime,
    cleanup_expired_sessions,
    close_session,
    execute_session_operation,
    execute_session_plan,
    get_session,
    inspect_session_dialogs,
    inspect_session_pages,
    observe_session_page,
    open_session,
    select_session_page,
)
from dingdongditch.authentication import (
    AuthEvent, AuthEventType, AuthenticationCallbacks, AuthenticationCapability,
    AuthenticationError, AuthenticationFailureKind, MappingSecretProvider,
    ProfileInfo, ProfileManager, SecretProvider, SecretReference,
    SecretResolutionReceipt, SecretValue, redact,
    PORTABLE_STATE_SCHEMA_VERSION, PortableStateFeature, PortableStatePolicy,
    PortableStateReceipt,
    CallbackWebAuthnTransport, WebAuthnParticipationReceipt,
    WebAuthnParticipationRequest, WebAuthnParticipationStatus, WebAuthnTransport,
    WebAuthnTransportEvent, WebAuthnTransportResult,
)
from dingdongditch.machine_contract import (
    MACHINE_CONTRACT_VERSION,
    ContractValidationError,
    PlanDocument,
    ValidationIssue,
    execution_plan_schema,
    execution_plan_tool,
    execution_receipt_schema,
    execution_schema,
    observation_schema,
    operation_schema,
    parse_execution_plan,
    parse_execution_receipt,
    parse_operation,
    parse_plan_document,
    parse_plan_receipt,
    parse_receipt,
    plan_document_schema,
    plan_receipt_schema,
    published_schema_resource,
    public_schema_names,
    serialize_execution_plan,
    serialize_plan_document,
)

__all__ = [
    "__version__",
    "Operation",
    "OperationGuard",
    "GuardBranch",
    "TargetAbsentGuard",
    "Action",
    "ActionType",
    "KeyPressScope",
    "SelectMode",
    "WaitCondition",
    "WaitConditionType",
    "LoadState",
    "Locator",
    "LocatorStrategy",
    "FreshnessPolicy",
    "PageConditionType",
    "FragmentPolicy",
    "PageCondition",
    "PagePrecondition",
    "PageConditionResultValue",
    "PageConditionResult",
    "PagePreconditionEvaluation",
    "Expectation",
    "ExpectationType",
    "NetworkUrlMatchMode",
    "NetworkArtifactKind",
    "NetworkArtifactRequest",
    "DialogType",
    "DialogAction",
    "DialogRequirement",
    "DialogContract",
    "ScreenshotPolicy",
    "ScreenshotConfig",
    "DesktopRedactionRegion",
    "Verdict",
    "ExecutionReceipt",
    "execute_operation",
    "execute_plan",
    "ExecutionPlan",
    "PlanReceipt",
    "PlanVerdict",
    "CompletionStatus",
    "FailurePolicy",
    "TargetConstraint",
    "ConstraintType",
    "AttributeOperator",
    "NameMatchMode",
    "CardinalityPolicy",
    "BrowserConfig",
    "BrowserProvider",
    "BrowserEngine",
    "BrowserChannel",
    "BrowserProfile",
    "default_browser_config",
    "AuthEvent", "AuthEventType", "AuthenticationCallbacks",
    "AuthenticationCapability", "AuthenticationError", "AuthenticationFailureKind",
    "MappingSecretProvider", "ProfileInfo", "ProfileManager", "SecretProvider",
    "SecretReference", "SecretResolutionReceipt", "SecretValue", "redact",
    "PORTABLE_STATE_SCHEMA_VERSION", "PortableStateFeature", "PortableStatePolicy",
    "PortableStateReceipt",
    "WebAuthnParticipationRequest", "WebAuthnParticipationReceipt",
    "WebAuthnParticipationStatus", "WebAuthnTransport", "WebAuthnTransportEvent",
    "WebAuthnTransportResult", "CallbackWebAuthnTransport",
    "PlanBuilder",
    "inspect_target",
    "list_dialog_history",
    "observe_page",
    "SessionCheckpoint",
    "SessionPhase",
    "SessionStatus",
    "TypingFocusPolicy",
    "TypingSession",
    "TypingSessionConfig",
    "TypingSessionResult",
    "TypingKeyReceipt",
    "DownloadRequest",
    "DownloadPolicy",
    "DownloadCollisionPolicy",
    "DownloadChecksumPolicy",
    "DownloadPageEffectPolicy",
    "DownloadTriggerAction",
    "DownloadLifecycleState",
    "DownloadFailureReason",
    "DownloadMimeSource",
    "DownloadArtifact",
    "DownloadResult",
    "DownloadArtifactStore",
    "SafeFilenameResolver",
    "CollisionResolver",
    "DownloadIntegrityVerifier",
    "DownloadCoordinator",
    "DownloadEventMonitor",
    "StagingRecoveryManager",
    "TrustedDownloadConfig",
    "PointerMoveRequest",
    "PointerOrigin",
    "UploadAuthorization",
    "UploadValidationError",
    "ComboboxSelection",
    "PageObservation",
    "PageObservationOptions",
    "ObservationReference",
    "ObservationFreshnessResult",
    "SnapshotCore",
    "ObservationCommit",
    "ObservationTransactionEvidence",
    "ObservationTransactionState",
    "CandidateEvidenceLevel",
    "LocatorAttestation",
    "LocatorAttestationStatus",
    "ObservationEvidenceView",
    "PageObserver",
    "ContinuitySession",
    "ContinuityError",
    "SessionHeader",
    "SessionLifecycle",
    "CommandRecord",
    "CommandState",
    "BrowserBinding",
    "TransportKind",
    "TerminalClassification",
    "ApplicationLifecycleState",
    "PublicSessionStatus",
    "SessionFailureKind",
    "SessionInfo",
    "SessionObservation",
    "SessionOperationResult",
    "SessionPlanResult",
    "StatefulSessionError",
    "StatefulSessionRuntime",
    "open_session",
    "get_session",
    "observe_session_page",
    "execute_session_operation",
    "execute_session_plan",
    "inspect_session_pages",
    "select_session_page",
    "inspect_session_dialogs",
    "close_session",
    "cleanup_expired_sessions",
    "ApplicationLifecycleEvidence",
    "ApplicationLifecycleAdapter",
    "ChatGPTApplicationLifecycleAdapter",
    "GeminiApplicationLifecycleAdapter",
    "UnknownApplicationLifecycleAdapter",
    "select_application_lifecycle_adapter",
    "MACHINE_CONTRACT_VERSION",
    "PlanDocument",
    "ValidationIssue",
    "ContractValidationError",
    "plan_document_schema",
    "execution_schema",
    "execution_plan_schema",
    "execution_plan_tool",
    "operation_schema",
    "observation_schema",
    "execution_receipt_schema",
    "plan_receipt_schema",
    "public_schema_names",
    "published_schema_resource",
    "parse_plan_document",
    "parse_execution_plan",
    "parse_operation",
    "serialize_plan_document",
    "serialize_execution_plan",
    "parse_execution_receipt",
    "parse_plan_receipt",
    "parse_receipt",
]
