"""Authoritative runtime capability limitations serialized in all receipts."""

RUNTIME_LIMITATIONS = (
    "playwright_bundled_chromium_firefox_webkit",
    "safari_not_supported",
    "playwright_only",
    "ordered_plans_stop_on_failure_only",
    "no_branches_loops_or_dags",
    "no_ai_planning",
    "no_autonomous_recovery",
    "no_locator_healing",
    "browser_visible_evidence_only",
    "no_external_world_truth_claims",
    "no_positional_index_selection",
    "no_arbitrary_sleep_action",
    "no_compound_wait_conditions",
    "iframe_declared_bounded_path_same_page_only",
    "no_frame_search_or_main_document_fallback",
    "native_dialogs_host_declared_only",
    "adaptive_plan_timeout_html5_media_only",
    "network_evidence_metadata_only_no_headers_or_bodies",
    "per_operation_har_unsupported",
    "portable_state_explicit_schema_v2",
    "no_secret_storage_or_credential_vault",
    "native_webauthn_authenticator_control_unsupported",
)
